language:
- java

services:
- mysql

jdk:
- oraclejdk7

before_install:

- mysql -u root --default-character-set=utf8 acme-patronage < Scripts/Create-Acme-Patronage-Full-Populate.sql

script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V 
- mvn test -B

dist:
- precise

sudo:
- false
